config/routes.rb
Rails.application.routes.draw do
  root :to => 'news#index'
  resources :comments do
    collection do
      get :newcomments
    end
  end

  resources :users do
    collection do
      post :login
      get :logout
      get :about
    end
  end
  get 'login', to: 'users#index'
  resources :news

  namespace :v0 do
    resources :comment, only: [:index, :show]
    resources :new, only: [:index, :show, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :new
  validates :content, length: { in: 3...1000 }
end

app/models/new.rb
class New < ApplicationRecord
  has_many :comments
  belongs_to :user

  validates :title, length: { in: 10...200 }
  validates :source, allow_blank: true, format: { with: /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/\/=]*)/, message: 'is invalid url' }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :new
  has_many :comments

  validates :username, length: { in: 2..15 }, uniqueness: { message: 'has been used' }
  validates :password, format: { with: /\A[-a-zA-Z\d_]+\z/, message: 'can only contain letters, digits, dashes and underscores' }, length: { minimum: 10 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    User.find_by_id session[:user_id]
  end

  before_action :authencation
  def authencation
    if current_user.blank?
      redirect_to login_path, notice: "Login first!"
    end
  end

  def login_user(user)
    session[:user_id] = user.id
  end

  def logout_user
    session[:user_id] = nil
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @new = New.find(params[:id])
    @comments = @new.comments.order(created_at: :desc)
  end

  def newcomments
    @comments = Comment.all.limit(3).order(created_at: :desc)
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = current_user.comments.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_back fallback_location: root_path, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_back fallback_location: root_path, notice: @comment.errors.full_messages.join(',') }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :new_id)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  skip_before_action :authencation, only: [:index]

  # GET /news
  # GET /news.json
  def index
    @page = (params[:p] || 0).to_i
    @start = @page * 8
    @news = New.all.offset(@start).limit(8).order(created_at: :desc)
    @has_more = (New.all.size - 8 * (@page + 1)) > 0
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = current_user.new.new
  end

  # POST /news
  # POST /news.json
  def create
    @news = current_user.new.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to news_index_url, notice: 'New was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_url, notice: 'New was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_news
    @news = New.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def news_params
    params.require(:new).permit(:title, :source)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  skip_before_action :authencation, only: [:index, :login, :new, :create, :about]

  # GET /users
  # GET /users.json
  def index
    @user = User.new
  end

  def login
    user = User.find_by(username: user_params[:username])&.authenticate(user_params[:password])
    if user
      login_user user
      redirect_to user_path(user.id), notice: 'Log in success!'
    else
      redirect_to users_path, notice: 'Something Wrong'
    end
  end

  def logout
    logout_user
    redirect_to news_index_url
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        login_user @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def about

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/controllers/v0/comment_controller.rb
class V0::CommentController < ActionController::Base

  # get http://localhost:3000/v0/comment.json
  def index
    @comments = Comment.all
  end

  # get http://localhost:3000/v0/comment/1.json
  def show
    @comment = Comment.find(params[:id])
  end
end

app/controllers/v0/new_controller.rb
class V0::NewController < ActionController::Base

  # get http://localhost:3000/v0/new.json
  def index
    @news = New.all
  end

  # get http://localhost:3000/v0/new/1.json
  def show
    @new = New.find(params[:id])
  end

  # post http://localhost:3000/v0/new
  def create
    user = User.find_by_username(params[:username])
    @new = user.new.new(title: params[:text], source: params['new source'])
    p params['new source']
    @new.save!
    render json: {message: 'ok'}, status: 200
  rescue => e
    render json: {message: 'bad'}, status: 400
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true, html: {class: 'form-group'}) do |form| %>
  <%= render 'layouts/alert', object: comment %>

  <div class="field">
    <%= form.hidden_field :new_id %>
    <%= form.text_area :content, id: :comment_content, class: 'form-control', rows: 5 %>
  </div>

  <%= form.submit "add comment", class: 'btn btn-success green'%>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<% content_for :title, @new.title %>

<p id="notice"><%= notice %></p>

<div class="topics media comment-index">
  <%= render "news/topic", new: @new%>
</div>
<%= render 'comments/form', comment: @new.comments.new %>

<div class="media comments">
  <% @comments.each do |comment| %>
    <div class="panel comment">
      <div class="">
        <%= "by #{comment.user.username} #{time_ago_in_words(comment.created_at)} ago" %>
      </div>
      <div class="media-body ml-1">
        <h4 class="media-heading"><%= comment.content %></h4>
      </div>
    </div>
  <% end %>
</div>

<br>

app/views/comments/new.html.erb
<% content_for :title, 'New Comments' %>

<div class="media comments">
  <% @comments.each do |comment| %>
    <div class="comment panel">
      <div class="">
        <%= "#{comment.user.username} #{time_ago_in_words(comment.created_at)} ago | on: #{comment.new.title}" %>
      </div>
      <div class="media-body ml-1">
        <h4 class="media-heading"><%= comment.content %></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/newcomments.html.erb
<% content_for :title, 'New Comments' %>

<div class="media comments">
  <% @comments.each do |comment| %>
    <div class="comment panel">
      <div class="">
        <%= "#{comment.user.username} #{time_ago_in_words(comment.created_at)} ago | on: #{comment.new.title}" %>
      </div>
      <div class="media-body ml-1">
        <h4 class="media-heading"><%= comment.content %></h4>
      </div>
    </div>
  <% end %>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/_alert.html.erb
<% if object.errors.any? %>
  <div >
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li class="alert alert-danger fade in"><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <% if content_for?(:title) %>
      <title><%= yield(:title) %></title>
    <% else %>
      <%= content_tag :title, 'Home' %>
    <% end %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="ui fixed stackable menu">
      <a class="header item" href="https://news.ycombinator.com/">
        <%= image_tag "icon.png", class: 'logo' %>
        RMIT News
      </a>
      <%= link_to 'Home', news_index_path, class: "item #{current_page?(news_index_path) ? 'active' : ''}" %>
      <%= link_to 'comments' , newcomments_comments_path, class: "item #{current_page?(newcomments_comments_path) ? 'active' : ''}" %>
      <%= link_to 'submit' , new_news_path, class: "item #{current_page?(new_news_path) ? 'active' : ''}" %>
      <div class="right menu">
        <% if current_user %>
          <%= link_to current_user.username, user_path(current_user.id), class: 'ui item' %>
          <%= link_to 'Log out', logout_users_path, class: 'ui item' %>
        <% else %>
          <%= link_to 'Log in', users_path, class: 'ui item' %>
        <% end %>
      </div>
    </div>
    <div class="ui main text container">
      <%= yield %>
    </div>

    <footer class="page-footer navbar-fixed-bottom">
      <div class="footer-copyright py-3 text-center">
          <a href="https://github.com/pigfly/RMIT-CSIT-RAD/tree/master/2018_S1/assignment2"> API </a>
          |
          <a href="/users/about"> About </a>
      </div>
    </footer>
  </body>
</html>

app/views/news/_form.html.erb
<%= form_with(model: news, local: true, url: news_index_path, html: {class: 'form-group'}) do |form| %>
  <%= render 'layouts/alert', object: news %>

  <div class="field">
    <%= form.label :title, 'title: ' %>
    <%= form.text_area :title, id: :news_title, class: 'form-control', rows: 5, placeholder: 'required' %>
  </div>

  <div class="field">
    <%= form.label :source, 'news source (optional): ' %>
    <%= form.url_field :source, id: :news_source, placeholder: 'https://', class: 'form-control' %>
  </div>

  <%= form.submit class: 'btn btn-success green' %>
<% end %>

app/views/news/_topic.html.erb
<div class="panel topic">
  <div class="media-body">
    <% prefix = @start ? "#{@start + index + 1}. " : ''%>
    <h4 class="media-heading"><%= "#{prefix}#{new.title} #{new.source.present? ? "(#{link_to new.source, new.source})" : '' }".html_safe %></h4>
  </div>
  <div class="ml-1">
    <span>by</span>
    <span class="strong"><%= new.user.username %></span>
    <span><%= "#{time_ago_in_words(new.created_at)} ago" %></span>
    <% comment_size = new.comments.size %>
    <span class="comment pull-right"><%= link_to "#{comment_size > 0 ? new.comments.size.to_s + ' comments' : 'no comments'}", comments_path(id: new.id) %></span>
  </div>
</div>

app/views/news/index.html.erb
<%= content_for :title, "Home Page #{@page}" %>
<% if notice %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>
<% if @news.present? %>
  <div class="topics media news-index">
    <% @news.each_with_index do |new, index| %>
      <%= render "topic", index: index, new: new%>
    <% end %>
  </div>
  <% if @has_more %>
    <div class="">
      <%= link_to 'More', news_index_path(p: @page + 1), class: 'btn btn-default' %>
    </div>
  <% end %>
<% else %>
  <h3>NO NEWS IS GOOD NEW!</h3>
<% end %>

app/views/news/new.html.erb
<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path, class: 'btn btn-default' %>

app/views/users/_form.html.erb
<% botton_text ||= 'Submit' %>
<%= form_with(model: user, local: true, html: {class: 'ui large form'}) do |form| %>
  <%= render 'layouts/alert', object: user %>

  <div class="field">
    <div class="ui left icon input">
      <i class="user icon"></i>
      <%= form.text_field :username, id: :user_username, placeholder: 'user name' %>
    </div>
  </div>

  <div class="field">
    <div class="ui left icon input">
      <i class="lock icon"></i>
      <%= form.password_field :password, id: :user_password, placeholder: 'password' %>
    </div>
  </div>

  <%= form.submit botton_text, class: 'ui fluid large teal submit button' %>
<% end %>

app/views/users/about.html.erb
<ul class="list-group">
  <li class="list-group-item">junliang.jiang@rmit.edu.au</li>
  <li class="list-group-item">anto.dominic@rmit.edu.au</li>
  <li class="list-group-item">andy.song@rmit.edu.au</li>
</ul>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', user_path(@user), class: 'btn btn-default' %>

app/views/users/index.html.erb
<div class="ui middle aligned center grid">
  <div class="column">
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% end %>

    <h3>Login</h3>

    <%= form_for @user, url: login_users_path, html: {class: 'ui large form'} do |form| %>

      <div class="field">
        <div class="ui left icon input">
          <i class="user icon"></i>
          <%= form.text_field :username, id: :user_username, placeholder: 'user name' %>
        </div>
      </div>

      <div class="field">
        <div class="ui left icon input">
          <i class="lock icon"></i>
          <%= form.password_field :password, id: :user_password, placeholder: 'password' %>
        </div>
      </div>

      <%= form.submit "Log in", class: 'ui fluid large teal submit button' %>
    <% end %>

    <h3>Create Account</h3>

    <%= render 'form', user: @user, botton_text: 'create' %>
    <style>
      body {
        text-align: center;
      }
      .column {
          max-width: 50%;
          margin-left: 24%;
      }
      @media(max-width: 767px) {
        .column {
          max-width: 80%;
          margin-left: 9%;
        }
      }
    </style>
  </div>
</div>

app/views/users/new.html.erb
<h1>Create Account</h1>

<%= render 'form', user: @user, botton_text: 'create' %>

app/views/users/show.html.erb
<% if notice %>
  <div class="alert alert-success" role="alert"><%= notice %></div>
<% end %>
<p class="grid-user">
  <span class="label label-info"><strong>Username:</strong></span>
  <%= @user.username %>
</p>

<p class="grid-user">
  <span class="label label-info"><strong>Password:</strong></span>
  <%= '*' * 8 %>
</p>

<%= link_to 'Edit User', edit_user_path(@user), class: 'btn btn-success' %>
<%= link_to 'Home', news_index_path, class: 'btn btn-primary' %>